FROM node:20-alpine3.16

WORKDIR /app
COPY ./nest-app .
RUN env > .env
#COPY ./nest-app/package*.json ./
RUN npm install
RUN npm run build

EXPOSE 8080

#CMD [ "npm", "run", "start:prod" ]
CMD [ "npm", "run", "start:dev" ]