version: '3'

services:
  postgres:
    container_name: "postgres"
    image: postgres:15-alpine 
    restart: on-failure
    networks:
      - nestjs-postgres
      - pgadmin-postgres
    env_file:
      - .env

  pgadmin:
    container_name: "pgadmin"
    image: dpage/pgadmin4:7.1
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - pgadmin-postgres
    ports:
      - 5050:80
    env_file:
      - .env

  nestjs:
    container_name: "nestjs"
    build:
      context: ./requirements/nest.js
      dockerfile: dockerfile
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - nginx-nestjs
    env_file:
      - .env

  nextjs:
    container_name: "nextjs"
    build:
      context: ./requirements/next.js
      dockerfile: dockerfile
    restart: on-failure
    networks:
      - nginx-nextjs
    env_file:
      - .env

  nginx:
    container_name: "nginx"
    image: nginx:1.25.0-alpine
    restart: on-failure
    networks:
      - nginx-nestjs
      - nginx-nextjs
    depends_on:
      - nestjs
      - nextjs
    ports:
      - 80:80
    volumes:
      - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf
    env_file:
      - .env

networks:
  nestjs-postgres:
    driver: bridge
  pgadmin-postgres:
    driver: bridge
  nginx-nestjs:
    driver: bridge
  nginx-nextjs:
    driver: bridge
