version: '3'

services:
  postgres:
    container_name: "postgres"
    image: postgres:15-alpine 
    restart: on-failure
    networks:
      - nest.js-Postgres
    env_file:
      - .env

  nest.js:
    container_name: "nest.js"
    build:
      context: ./requirements/nest.js
      dockerfile: dockerfile
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - nginx-nest.js
      - next.js-nest.js
      - nest.js-Postgres
    env_file:
      - .env

  # next.js:
  #   container_name: "next.js"
  #   build:
  #     context: ./requirements/next.js
  #     dockerfile: dockerfile
  #   depends_on:
  #     - Postgres
  #     - nest.js
  #   restart: on-failure
  #   networks:
  #     - next.js-nest.js
  #     - nginx-next.js
  #   env_file:
  #     - .env

  nginx:
    container_name: "nginx"
    image: nginx:1.25.0-alpine
    restart: on-failure
    networks:
      - nginx-nest.js
      - nginx-next.js
    depends_on:
      - nest.js
      # - next.js
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    env_file:
      - .env

networks:
  next.js-nest.js:
    driver: bridge
  nest.js-Postgres:
    driver: bridge
  nginx-nest.js:
    driver: bridge
  nginx-next.js:
    driver: bridge
