version: '3'

services:
  postgres:
    container_name: "postgres"
    image: postgres:15-alpine 
    restart: on-failure
    networks:
      - nestjs-postgres
    env_file:
      - .env

  nestjs:
    container_name: "nestjs"
    build:
      context: ./requirements/nest.js
      dockerfile: dockerfile
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - nginx-nestjs
      - nextjs-nestjs
      - nestjs-postgres
    env_file:
      - .env

  # nextjs:
  #   container_name: "nextjs"
  #   build:
  #     context: ./requirements/next.js
  #     dockerfile: dockerfile
  #   restart: on-failure
  #   networks:
  #     - nextjs-nestjs
  #     - nginx-nextjs
  #   env_file:
  #     - .env

  nginx:
    container_name: "nginx"
    image: nginx:1.25.0-alpine
    restart: on-failure
    networks:
      - nginx-nestjs
      - nginx-nextjs
    depends_on:
      - nestjs
      # - nextjs
    ports:
      - 80:80
    volumes:
      - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf
    env_file:
      - .env

networks:
  nextjs-nestjs:
    driver: bridge
  nestjs-postgres:
    driver: bridge
  nginx-nestjs:
    driver: bridge
  nginx-nextjs:
    driver: bridge
