import { Content } from "@/types/ContentType";

export const mocContentData: Content[] = [
  {
    uId: 1,
    profileImage: "https://i.pravatar.cc/150?img=1",
    userNickName: "user1",
    Date: "05월 22일 10시 30분",
    Content: "Lorem ipsum dolor sit amet",
    isTo: false,
  },
  {
    uId: 2,
    profileImage: "https://i.pravatar.cc/150?img=2",
    userNickName: "user2",
    Date: "05월 22일 11시 45분",
    Content: "consectetur adipiscing elit",
    isTo: false,
  },
  {
    uId: 3,
    profileImage: "https://i.pravatar.cc/150?img=3",
    userNickName: "user3",
    Date: "05월 22일 14시 20분",
    Content: "sed do eiusmod tempor incididunt",
    isTo: false,
  },
  {
    uId: 4,
    profileImage: "https://i.pravatar.cc/150?img=4",
    userNickName: "user4",
    Date: "05월 23일 09시 15분",
    Content: "ut labore et dolore magna aliqua",
    isTo: false,
  },
  {
    uId: 5,
    profileImage: "https://i.pravatar.cc/150?img=5",
    userNickName: "user5",
    Date: "05월 23일 16시 50분",
    Content: "Ut enim ad minim veniam",
    isTo: false,
  },
  {
    uId: 6,
    profileImage: "https://i.pravatar.cc/150?img=6",
    userNickName: "user6",
    Date: "05월 24일 13시 40분",
    Content: "quis nostrud exercitation ullamco",
    isTo: false,
  },
  {
    uId: 7,
    profileImage: "https://i.pravatar.cc/150?img=7",
    userNickName: "user7",
    Date: "05월 25일 08시 55분",
    Content: "laboris nisi ut aliquip ex ea commodo",
    isTo: false,
  },
  {
    uId: 8,
    profileImage: "https://i.pravatar.cc/150?img=8",
    userNickName: "user8",
    Date: "05월 25일 15시 10분",
    Content:
      "consequat duis aute irure dolor in reprehenderit laboris nisi ut aliquip ex ea commodo",
    isTo: true,
  },
  {
    uId: 9,
    profileImage: "https://i.pravatar.cc/150?img=9",
    userNickName: "user9",
    Date: "05월 26일 11시 25분",
    Content: "voluptate velit esse cillum dolore",
    isTo: false,
  },
  {
    uId: 10,
    profileImage: "https://i.pravatar.cc/150?img=10",
    userNickName: "user10",
    Date: "05월 26일 16시 55분",
    Content: "eu fugiat nulla pariatur",
    isTo: false,
  },
];
