import { user } from "@/types/UserType";

export const mocUserData: user[] = [
  {
    uId: 1,
    profileImage: "https://example.com/profile1.jpg",
    userEmail: "user1@example.com",
    userNickName: "user1",
    stateOn: true,
  },
  {
    uId: 2,
    profileImage: "https://example.com/profile2.jpg",
    userEmail: "user2@example.com",
    userNickName: "user2",
    stateOn: false,
  },
  {
    uId: 3,
    profileImage: "https://example.com/profile3.jpg",
    userEmail: "user3@example.com",
    userNickName: "user3",
    stateOn: true,
  },
  {
    uId: 4,
    profileImage: "https://example.com/profile4.jpg",
    userEmail: "user4@example.com",
    userNickName: "user4",
    stateOn: true,
  },
  {
    uId: 5,
    profileImage: "https://example.com/profile5.jpg",
    userEmail: "user5@example.com",
    userNickName: "user5",
    stateOn: false,
  },
  {
    uId: 6,
    profileImage: "https://example.com/profile6.jpg",
    userEmail: "user6@example.com",
    userNickName: "user6",
    stateOn: true,
  },
  {
    uId: 7,
    profileImage: "https://example.com/profile7.jpg",
    userEmail: "user7@example.com",
    userNickName: "user7",
    stateOn: true,
  },
  {
    uId: 8,
    profileImage: "https://example.com/profile8.jpg",
    userEmail: "user8@example.com",
    userNickName: "user8",
    stateOn: false,
  },
  {
    uId: 9,
    profileImage: "https://example.com/profile9.jpg",
    userEmail: "user9@example.com",
    userNickName: "user9",
    stateOn: true,
  },
  {
    uId: 10,
    profileImage: "https://example.com/profile10.jpg",
    userEmail: "user10@example.com",
    userNickName: "user10",
    stateOn: true,
  },
  {
    uId: 11,
    profileImage: "https://example.com/profile11.jpg",
    userEmail: "user11@example.com",
    userNickName: "user11",
    stateOn: false,
  },
  {
    uId: 12,
    profileImage: "https://example.com/profile12.jpg",
    userEmail: "user12@example.com",
    userNickName: "user12",
    stateOn: true,
  },
  {
    uId: 13,
    profileImage: "https://example.com/profile13.jpg",
    userEmail: "user13@example.com",
    userNickName: "user13",
    stateOn: true,
  },
  {
    uId: 14,
    profileImage: "https://example.com/profile14.jpg",
    userEmail: "user14@example.com",
    userNickName: "user14",
    stateOn: false,
  },
];
